export const travels = [
  {
    id_viaje: 7,
    fecha_salida: "2025-05-12T08:00:00.000Z",
    hora_salida_programada: "08:00:00",
    hora_salida_real: "08:00:00",
    costo: "90.5",
    id_bus: 2,
    id_ruta: 7,
    id_chofer: 2,
    id_pago: 2,
    bus: {
      id_bus: 2,
      placa: "1234ABC",
      marca: "Volvo",
      modelo: "2022X",
      año_modelo: 2022,
      tipo_bus: "CAMA",
      estado: "Operativo",
      id_agencia: 3,
      asientos: [
        {
          id_asiento: 43,
          numero: "3",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 44,
          numero: "4",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 45,
          numero: "5",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 46,
          numero: "6",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 47,
          numero: "7",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 48,
          numero: "8",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 49,
          numero: "9",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 50,
          numero: "10",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 51,
          numero: "11",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 52,
          numero: "12",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 53,
          numero: "13",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 54,
          numero: "14",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 55,
          numero: "15",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 56,
          numero: "16",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 57,
          numero: "17",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 58,
          numero: "18",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 59,
          numero: "19",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 60,
          numero: "20",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 61,
          numero: "21",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 62,
          numero: "22",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 63,
          numero: "23",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 64,
          numero: "24",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 65,
          numero: "25",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 66,
          numero: "26",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 67,
          numero: "27",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 68,
          numero: "28",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 69,
          numero: "29",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 70,
          numero: "30",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 71,
          numero: "31",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 72,
          numero: "32",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 73,
          numero: "33",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 74,
          numero: "34",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 75,
          numero: "35",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 76,
          numero: "36",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 77,
          numero: "37",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 78,
          numero: "38",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 79,
          numero: "39",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 80,
          numero: "40",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 41,
          numero: "1",
          ubicacion: "Superior",
          estado: "Reservado",
          id_bus: 2,
        },
        {
          id_asiento: 42,
          numero: "2",
          ubicacion: "Superior",
          estado: "Reservado",
          id_bus: 2,
        },
      ],
    },
    chofer: {
      id_chofer: 2,
      nombre: "Juan",
      apellido: "Mamani",
      carnet_identidad: "1234567LP",
      numero_celular: "78945612",
      categoria_licencia: "B",
      direccion_contacto: "Calle 12 de Octubre, El Alto",
      estado: "Activo",
      id_agencia: 3,
    },
    ruta: {
      id_ruta: 7,
      origen: "Sucre",
      parada_intermedia: "Potosí",
      destino: "Oruro",
      distancia: "350km",
      tiempo_estimado: "6",
      camino: "Asfaltado",
    },
    reserva: [],
    pago: {
      id_pago: 2,
      ruta_codigo_qr: "https://pagos.bo/qr/abc123",
      fecha_creacion: "2025-05-30T16:40:16.084Z",
      estado: "Activo",
      id_agencia: 3,
    },
  },
  {
    id_viaje: 8,
    fecha_salida: "2025-05-13T08:00:00.000Z",
    hora_salida_programada: "08:00:00",
    hora_salida_real: "08:00:00",
    costo: "95.5",
    id_bus: 2,
    id_ruta: 8,
    id_chofer: 2,
    id_pago: 2,
    bus: {
      id_bus: 2,
      placa: "1234ABC",
      marca: "Volvo",
      modelo: "2022X",
      año_modelo: 2022,
      tipo_bus: "CAMA",
      estado: "Operativo",
      id_agencia: 3,
      asientos: [
        {
          id_asiento: 43,
          numero: "3",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 44,
          numero: "4",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 45,
          numero: "5",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 46,
          numero: "6",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 47,
          numero: "7",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 48,
          numero: "8",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 49,
          numero: "9",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 50,
          numero: "10",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 51,
          numero: "11",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 52,
          numero: "12",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 53,
          numero: "13",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 54,
          numero: "14",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 55,
          numero: "15",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 56,
          numero: "16",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 57,
          numero: "17",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 58,
          numero: "18",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 59,
          numero: "19",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 60,
          numero: "20",
          ubicacion: "Superior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 61,
          numero: "21",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 62,
          numero: "22",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 63,
          numero: "23",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 64,
          numero: "24",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 65,
          numero: "25",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 66,
          numero: "26",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 67,
          numero: "27",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 68,
          numero: "28",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 69,
          numero: "29",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 70,
          numero: "30",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 71,
          numero: "31",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 72,
          numero: "32",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 73,
          numero: "33",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 74,
          numero: "34",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 75,
          numero: "35",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 76,
          numero: "36",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 77,
          numero: "37",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 78,
          numero: "38",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 79,
          numero: "39",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 80,
          numero: "40",
          ubicacion: "Inferior",
          estado: "Disponible",
          id_bus: 2,
        },
        {
          id_asiento: 41,
          numero: "1",
          ubicacion: "Superior",
          estado: "Reservado",
          id_bus: 2,
        },
        {
          id_asiento: 42,
          numero: "2",
          ubicacion: "Superior",
          estado: "Reservado",
          id_bus: 2,
        },
      ],
    },
    chofer: {
      id_chofer: 2,
      nombre: "Juan",
      apellido: "Mamani",
      numero_celular: "78945612",
      categoria_licencia: "B",
      direccion_contacto: "Calle 12 de Octubre, El Alto",
      estado: "Activo",
      id_agencia: 3,
    },
    ruta: {
      origen: "Tarija",
      parada_intermedia: "Camiri",
      destino: "Santa Cruz",
      distancia: "410km",
      tiempo_estimado: "8",
      camino: "Asfaltado",
    },
    reserva: [],
    pago: {
      id_pago: 2,
      ruta_codigo_qr: "https://pagos.bo/qr/abc123",
      fecha_creacion: "2025-05-30T16:40:16.084Z",
      estado: "Activo",
      id_agencia: 3,
    },
  },
];
