[
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "80.5",
    "fecha_salida": "2025-07-10T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 5,
    "id_viaje": 18,
    "reserva": ["[Object]", "[Object]"],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "380km",
      "id_agencia": 3,
      "id_ruta": 5,
      "origen": "La Paz",
      "parada_intermedia": "Oruro",
      "tiempo_estimado": "7"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "85.5",
    "fecha_salida": "2025-07-11T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 6,
    "id_viaje": 19,
    "reserva": ["[Object]"],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "480km",
      "id_agencia": 3,
      "id_ruta": 6,
      "origen": "Santa Cruz",
      "parada_intermedia": "Montero",
      "tiempo_estimado": "9"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "90.5",
    "fecha_salida": "2025-07-12T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 7,
    "id_viaje": 20,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Oruro",
      "distancia": "350km",
      "id_agencia": 3,
      "id_ruta": 7,
      "origen": "Sucre",
      "parada_intermedia": "Potosí",
      "tiempo_estimado": "6"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "95.5",
    "fecha_salida": "2025-07-13T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 8,
    "id_viaje": 21,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Santa Cruz",
      "distancia": "410km",
      "id_agencia": 3,
      "id_ruta": 8,
      "origen": "Tarija",
      "parada_intermedia": "Camiri",
      "tiempo_estimado": "8"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "100.5",
    "fecha_salida": "2025-07-14T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 5,
    "id_viaje": 22,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "380km",
      "id_agencia": 3,
      "id_ruta": 5,
      "origen": "La Paz",
      "parada_intermedia": "Oruro",
      "tiempo_estimado": "7"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "105.5",
    "fecha_salida": "2025-07-15T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 6,
    "id_viaje": 23,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "480km",
      "id_agencia": 3,
      "id_ruta": 6,
      "origen": "Santa Cruz",
      "parada_intermedia": "Montero",
      "tiempo_estimado": "9"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "110.5",
    "fecha_salida": "2025-07-16T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 7,
    "id_viaje": 24,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Oruro",
      "distancia": "350km",
      "id_agencia": 3,
      "id_ruta": 7,
      "origen": "Sucre",
      "parada_intermedia": "Potosí",
      "tiempo_estimado": "6"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "115.5",
    "fecha_salida": "2025-07-17T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 8,
    "id_viaje": 25,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Santa Cruz",
      "distancia": "410km",
      "id_agencia": 3,
      "id_ruta": 8,
      "origen": "Tarija",
      "parada_intermedia": "Camiri",
      "tiempo_estimado": "8"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "120.5",
    "fecha_salida": "2025-07-18T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 5,
    "id_viaje": 26,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "380km",
      "id_agencia": 3,
      "id_ruta": 5,
      "origen": "La Paz",
      "parada_intermedia": "Oruro",
      "tiempo_estimado": "7"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "125.5",
    "fecha_salida": "2025-07-19T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 6,
    "id_viaje": 27,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "480km",
      "id_agencia": 3,
      "id_ruta": 6,
      "origen": "Santa Cruz",
      "parada_intermedia": "Montero",
      "tiempo_estimado": "9"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "130.5",
    "fecha_salida": "2025-07-20T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 7,
    "id_viaje": 28,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Oruro",
      "distancia": "350km",
      "id_agencia": 3,
      "id_ruta": 7,
      "origen": "Sucre",
      "parada_intermedia": "Potosí",
      "tiempo_estimado": "6"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "135.5",
    "fecha_salida": "2025-07-21T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 8,
    "id_viaje": 29,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Santa Cruz",
      "distancia": "410km",
      "id_agencia": 3,
      "id_ruta": 8,
      "origen": "Tarija",
      "parada_intermedia": "Camiri",
      "tiempo_estimado": "8"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "140.5",
    "fecha_salida": "2025-07-22T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 5,
    "id_viaje": 30,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "380km",
      "id_agencia": 3,
      "id_ruta": 5,
      "origen": "La Paz",
      "parada_intermedia": "Oruro",
      "tiempo_estimado": "7"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "145.5",
    "fecha_salida": "2025-07-23T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 6,
    "id_viaje": 31,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "480km",
      "id_agencia": 3,
      "id_ruta": 6,
      "origen": "Santa Cruz",
      "parada_intermedia": "Montero",
      "tiempo_estimado": "9"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "150.5",
    "fecha_salida": "2025-07-24T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 7,
    "id_viaje": 32,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Oruro",
      "distancia": "350km",
      "id_agencia": 3,
      "id_ruta": 7,
      "origen": "Sucre",
      "parada_intermedia": "Potosí",
      "tiempo_estimado": "6"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "155.5",
    "fecha_salida": "2025-07-25T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 8,
    "id_viaje": 33,
    "reserva": [],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Santa Cruz",
      "distancia": "410km",
      "id_agencia": 3,
      "id_ruta": 8,
      "origen": "Tarija",
      "parada_intermedia": "Camiri",
      "tiempo_estimado": "8"
    }
  },
  {
    "bus": {
      "asientos": "[Array]",
      "año_modelo": 2022,
      "estado": "Operativo",
      "id_agencia": 3,
      "id_bus": 2,
      "marca": "Volvo",
      "modelo": "2022X",
      "placa": "1234ABC",
      "tipo_bus": "CAMA"
    },
    "chofer": {
      "apellido": "Mamani",
      "carnet_identidad": "1234567LP",
      "categoria_licencia": "B",
      "direccion_contacto": "Calle 12 de Octubre, El Alto",
      "estado": "Activo",
      "id_agencia": 3,
      "id_chofer": 2,
      "nombre": "Juan",
      "numero_celular": "78945612"
    },
    "costo": "160.5",
    "fecha_salida": "2025-07-26T08:00:00.000Z",
    "hora_salida_programada": "08:00:00",
    "hora_salida_real": "08:00:00",
    "id_bus": 2,
    "id_chofer": 2,
    "id_pago": 2,
    "id_ruta": 5,
    "id_viaje": 34,
    "reserva": ["[Object]"],
    "ruta": {
      "camino": "Asfaltado",
      "destino": "Cochabamba",
      "distancia": "380km",
      "id_agencia": 3,
      "id_ruta": 5,
      "origen": "La Paz",
      "parada_intermedia": "Oruro",
      "tiempo_estimado": "7"
    }
  }
]